import type { System } from './schema'

const CONTRACT_ROLE = 'Architecture + led a small team · freelance contract'

export const SYSTEMS: System[] = [
  // ---------- FEATURED (6) ----------
  {
    slug: 'aiva',
    name: 'AIVA Chat',
    domain: 'Voice AI',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['Twilio', 'ElevenLabs', 'OpenAI', 'Node.js'],
    summary:
      'A platform for deploying AI voice agents and embeddable chat widgets across web, phone, and apps — with full call recordings, logs, and per-conversation analytics.',
    url: 'https://aivachat.io/',
    status: 'LIVE',
    featured: true,
  },
  {
    slug: 'health-wealth-safe',
    name: 'Health Wealth Safe',
    domain: 'Healthcare · EMR',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Node.js', 'Twilio', 'Jitsi', 'MySQL', 'AWS'],
    summary:
      'A healthcare platform handling patient records, EMR, and billing, with real-time chat and video consultations across separate patient and staff applications.',
    url: 'https://www.healthwealthsafe.com/',
    status: 'LIVE',
    featured: true,
  },
  {
    slug: 'vetwise',
    name: 'VetWise',
    domain: 'Veterinary telehealth',
    region: 'CA',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Redis', 'AWS'],
    summary:
      'After-hours veterinary phone support and virtual consultations across Canada, booked in three steps.',
    url: 'https://getvetwise.com/',
    status: 'LIVE',
    featured: true,
  },
  {
    slug: 'yellowpad',
    name: 'YellowPad AI',
    domain: 'Legal',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Python', 'OpenAI', 'LLM prompt engineering'],
    summary:
      'Document data infrastructure for legal work — automated drafting of contracts, briefs, and standard agreements with intelligent templates.',
    url: 'https://www.yellowpad.ai/',
    status: 'LIVE',
    featured: true,
  },
  {
    slug: 'quickhub',
    name: 'Quick Hub',
    domain: 'Reputation · marketing',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Nest.js', 'GraphQL', 'Prisma', 'OpenAI'],
    summary:
      'An AI operating system for local business: review management, campaign automation, social scheduling, and WhatsApp automation in one console.',
    url: 'https://www.quickhub.ai/',
    status: 'LIVE',
    featured: true,
  },
  {
    slug: 'sydon',
    name: 'Sydon AI',
    domain: 'Agentic commerce',
    region: 'US',
    year: 2026,
    role: CONTRACT_ROLE,
    stack: ['OpenAI', 'AI agents', 'Data analytics', 'Amazon FBA'],
    summary:
      'An agentic operating system for commerce — account health, margin and FBA insight, competitor analysis, plus AI-driven outreach and reply automation.',
    url: 'https://sydon.ai/',
    status: 'LIVE',
    featured: true,
  },

  // ---------- ARCHIVE (12) ----------
  {
    slug: 'frontdesk-clinic',
    name: 'FrontDesk Clinic',
    domain: 'Healthcare automation',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Node.js', 'OpenAI', 'Twilio'],
    summary:
      'Secure phone, fax, and text for healthcare practices, with an AI assistant handling scheduling, reminders, refills, and insurance verification.',
    url: 'https://frontdesk.clinic/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'mof-frontdesk',
    name: 'MOF FrontDesk AI',
    domain: 'Healthcare automation',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Node.js', 'PostgreSQL', 'OpenAI', 'Twilio', 'AWS'],
    summary:
      'An AI phone agent for medical offices: books, cancels, and reschedules appointments, with call logs, transcription, and a configurable agent voice.',
    // No url — client UAT environment behind a login. See spec §5.2.
    status: 'PRIVATE',
    featured: false,
  },
  {
    slug: 'hcomb',
    name: 'Hcomb',
    domain: 'Hiring · training',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Node.js', 'OpenAI'],
    summary:
      'AI-driven training and hiring — matches candidates to roles, automates job posting, and runs AI-conducted interviews.',
    url: 'https://www.hcomb.ai/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'corprite',
    name: 'CorpRite',
    domain: 'Governance · compliance',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Node.js', 'Blockchain', 'PostgreSQL'],
    summary:
      'Entity and equity management — secure records for shareholders, directors, and executives, with corporate governance tracking.',
    url: 'https://corprite.co/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'krone',
    name: 'Krone',
    domain: 'Compliance consulting',
    region: 'DK',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Node.js', 'React'],
    summary:
      'A Danish consultancy platform covering compliance, anti-corruption, financial management, and ESG advisory.',
    url: 'https://www.krone.one/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'advancedcare',
    name: 'AdvancedCare',
    domain: 'Healthcare · RCM',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Node.js', 'PostgreSQL', 'AWS'],
    summary:
      'Healthcare revenue-cycle management and EHR — patient data, telehealth consultation, and insurance claims processing.',
    url: 'https://advancedcare.com/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'pco-intelligence',
    name: 'PCO Intelligence',
    domain: 'Conversational AI',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['Amazon Lex', 'Amazon Connect', 'AWS Lambda'],
    summary:
      'AI-handled customer queries over a cloud call centre, with custom widget support for voice and chatbot interaction.',
    url: 'https://pcointelligence.com/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'lalo',
    name: 'Lalo',
    domain: 'Consumer AI',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['OpenAI', 'Node.js', 'AWS'],
    // Caption written from the live site (private family media), NOT the deck's
    // stale "free AI obituary writer" description. Spec §5.4.
    summary:
      'A private family media platform. Built the OpenAI-backed generation service behind its written content features.',
    url: 'https://www.lalo.app/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'reknew',
    name: 'ReKnew AI',
    domain: 'Enterprise modernization',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Node.js', 'Python', 'PostgreSQL', 'MongoDB', 'Redis', 'OpenAI'],
    summary:
      'Data-platform modernization for enterprises — accelerating AI adoption and automating manual processes across legacy systems.',
    url: 'https://reknew.ai/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'omniai',
    name: 'OmniAI Chatbot',
    domain: 'Omnichannel support',
    region: 'US',
    year: 2025,
    role: CONTRACT_ROLE,
    stack: ['React', 'Node.js', 'Python', 'PostgreSQL', 'Dialogflow', 'Shopify API'],
    summary:
      'A unified inbox for WhatsApp, Instagram, and email, with sentiment-aware AI replies, human handoff, and Shopify order sync.',
    url: 'https://omniaichatbot.com/',
    status: 'LIVE',
    featured: false,
  },
  {
    slug: 'stockly',
    name: 'Stockly',
    domain: 'Fintech · social',
    region: 'US',
    year: 2024,
    role: CONTRACT_ROLE,
    stack: ['React', 'React Native', 'Node.js', 'Python', 'PostgreSQL', 'Polygon API'],
    summary:
      'A social platform for stock-market discussion, connecting users with investors, experts, and AI assistants over real-time financial data.',
    status: 'PRIVATE',
    featured: false,
  },
  {
    slug: 'flourish-therapy',
    name: 'Flourish Together Therapy',
    domain: 'Healthcare · booking',
    region: 'US',
    year: 2024,
    role: 'Chatbot design and integration · freelance contract',
    stack: ['Landbot', 'Asana', 'Zapier'],
    summary:
      'A booking chatbot for a therapy practice — matches therapists, surfaces insurance providers, and books appointments via Asana and Zapier.',
    url: 'https://www.flourishtogethertherapy.com/',
    status: 'LIVE',
    featured: false,
  },
]
